### ISSUE TITLE
output naming convention

### ISSUE THREAD

**Issue by crissonpl** [terraform-ibm-modules/terraform-ibm-observability#8]
the names of the output values for sysdig and logdna don't follow the same convetion.

like logdna_instance.logdna_instance_id vs sysdig_instance.sysdig_id

**Comment by umarali-nagoor** [comment]
Issue has been fixed as part of following PR on root module

https://github.com/terraform-ibm-modules/terraform-ibm-observability/pull/15

Hence closing the issue.
